<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\A3ITranslator.Application\A3ITranslator.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.AI.Translation.Text" Version="1.0.0" />
    <PackageReference Include="Google.Cloud.Speech.V1" Version="3.8.0" />
    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.46.0" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="8.0.0" />
    <PackageReference Include="OpenAI" Version="2.5.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
